// All user-facing texts (German) live here.
export const t = {
  appName: 'Who Drives?',
  common: {
    loading: 'Lädt …',
    genericError:
      'Das hat nicht geklappt. Bitte prüfe deine Internetverbindung und versuche es noch einmal.',
    retry: 'Nochmal versuchen',
    cancel: 'Abbrechen',
  },
  offline: {
    title: 'Keine Verbindung',
    text: 'Die App erreicht den Server gerade nicht. Bitte prüfe deine Internetverbindung und versuche es gleich noch einmal.',
  },
  profile: {
    title: 'Mein Profil',
    welcomeTitle: 'Willkommen!',
    welcomeText: 'Wie sollen dich die anderen in der Familie sehen?',
    nameLabel: 'Dein Name',
    namePlaceholder: 'z. B. Oma Gisela',
    nameRequired: 'Bitte gib einen Namen ein.',
    save: 'Speichern',
    saved: 'Gespeichert.',
    loggedInAs: (email: string) => `Angemeldet als ${email}`,
    logout: 'Abmelden',
    logoutTitle: 'Abmelden?',
    logoutText: 'Zum erneuten Anmelden brauchst du wieder einen Code per E-Mail.',
    appearance: 'Darstellung',
    themes: { light: 'Hell', dark: 'Dunkel' },
    privacy: 'Datenschutzerklärung',
    delete: 'Konto löschen',
    deleteTitle: 'Konto endgültig löschen?',
    deleteText:
      'Dein Name, deine E-Mail-Adresse und deine Mitgliedschaften werden gelöscht. ' +
      'Termine, die du übernommen hast, bleiben für die anderen als „ehemaliges Mitglied“ sichtbar. ' +
      'Bist du das letzte Mitglied deiner Familie, wird die Familie mit allen Kindern und Terminen gelöscht. ' +
      'Das lässt sich nicht rückgängig machen.',
    deleteConfirm: 'Endgültig löschen',
  },
  login: {
    title: 'Anmelden',
    emailLabel: 'Deine E-Mail-Adresse',
    emailPlaceholder: 'name@beispiel.de',
    sendCode: 'Code senden',
    codeSentTo: (email: string) => `Wir haben einen 6-stelligen Code an ${email} geschickt.`,
    codeLabel: 'Code aus der E-Mail',
    verify: 'Anmelden',
    otherEmail: 'Andere E-Mail-Adresse',
    invalidEmail: 'Bitte gib eine gültige E-Mail-Adresse ein.',
    invalidCode: 'Der Code ist falsch oder abgelaufen.',
  },
  family: {
    noFamilyTitle: 'Noch keine Familie',
    noFamilyText: 'Lege eine Familie an. Weitere Mitglieder lädst du später per Code ein.',
    joinText: 'Hast du einen Einladungscode bekommen? Dann gib ihn hier ein.',
    codeLabel: 'Einladungscode',
    join: 'Familie beitreten',
    invalidCode: 'Dieser Code ist ungültig, abgelaufen oder wurde schon benutzt.',
    orCreate: 'Oder: neue Familie anlegen',
    you: '(du)',
    remove: 'Aus der Familie entfernen',
    removeTitle: (name: string) => `${name} entfernen?`,
    removeText: 'Die Person sieht danach keine Termine dieser Familie mehr.',
    nameLabel: 'Name der Familie',
    namePlaceholder: 'z. B. Familie Müller',
    create: 'Familie anlegen',
    members: 'Mitglieder',
    unnamedMember: 'Ohne Namen',
    roles: { parent: 'Elternteil', grandparent: 'Großeltern', other: 'Weitere Person' },
  },
  invite: {
    title: 'Mitglied einladen',
    chooseRole: 'Als was lädst du die Person ein?',
    roleNote: 'Die Rolle ist nur eine Bezeichnung – alle Mitglieder haben die gleichen Rechte.',
    create: 'Code erstellen',
    codeIntro: (role: string) => `Einladungscode (${role}):`,
    validUntil: (date: string) => `Gilt bis ${date} und nur für eine Person.`,
    share: 'Code teilen',
    another: 'Weiteren Code erstellen',
    openTitle: 'Offene Einladungen',
    revoke: 'Zurückziehen',
    shareMessage: (family: string, code: string, date: string) =>
      `Du bist bei „Who Drives?“ in „${family}“ eingeladen. ` +
      `Öffne die App, melde dich an und gib diesen Code ein: ${code} (gültig bis ${date}).`,
  },
  children: {
    title: 'Kinder',
    none: 'Noch keine Kinder eingetragen.',
    add: 'Kind hinzufügen',
    nameLabel: 'Vorname',
    colorLabel: 'Farbe',
    nameRequired: 'Bitte gib einen Vornamen ein.',
    colors: {
      '#1E6FD9': 'Blau',
      '#2E9E44': 'Grün',
      '#E07B00': 'Orange',
      '#8E44AD': 'Lila',
      '#D63031': 'Rot',
      '#00979D': 'Türkis',
    },
  },
  events: {
    title: 'Termine verwalten',
    none: 'Noch keine Termine angelegt.',
    new: 'Neuer Termin',
    titleLabel: 'Was?',
    titlePlaceholder: 'z. B. Reiten',
    kindLabel: 'Art',
    kinds: { ride: 'Fahrt', pickup: 'Abholen', care: 'Betreuung', other: 'Sonstiges' },
    childLabel: 'Für welches Kind?',
    noChildren: 'Lege zuerst unter „Kinder“ ein Kind an.',
    locationLabel: 'Wo? (optional)',
    locationPlaceholder: 'z. B. Reitstall Sonnenhof',
    repeatLabel: 'Wie oft?',
    once: (date: string, time: string) => `Einmalig am ${date}, ${time} Uhr`,
    onceOption: 'Einmalig',
    weeklyOption: 'Jede Woche',
    firstDateLabel: 'Datum',
    firstDateWeeklyLabel: 'Erster Termin',
    untilDateLabel: 'Letzter Termin (optional)',
    noEndDate: 'Kein Enddatum',
    weekdayHint: (day: string) => `Wiederholt sich jeden ${day}.`,
    timeLabel: 'Uhrzeit',
    durationLabel: 'Dauer',
    durations: {
      15: '15 Min.',
      30: '30 Min.',
      45: '45 Min.',
      60: '1 Std.',
      90: '1½ Std.',
      120: '2 Std.',
      180: '3 Std.',
    },
    save: 'Termin speichern',
    weekdays: ['Sonntag', 'Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag'],
    weekly: (days: string, time: string, from: string, until: string | null) =>
      `Jeden ${days}, ${time} Uhr (ab ${from}${until ? ` bis ${until}` : ''})`,
    errors: {
      title: 'Bitte gib an, was ansteht.',
      child: 'Bitte wähle ein Kind aus.',
      date: 'Bitte wähle ein Datum.',
      time: 'Bitte wähle eine Uhrzeit.',
      duration: 'Bitte wähle eine Dauer.',
      untilBeforeFirst: 'Der letzte Termin liegt vor dem ersten.',
    },
  },
  occurrences: {
    today: 'Heute',
    tomorrow: 'Morgen',
    cancelled: 'Abgesagt',
    cancelHint: 'Tippen zum Absagen',
    cancelTitle: (title: string, day: string) => `„${title}“ (${day}) absagen?`,
    cancelText: 'Der Termin wird für alle als abgesagt angezeigt.',
    cancel: 'Termin absagen',
    until: (time: string) => `bis ${time} Uhr`,
    open: 'Noch offen – wer übernimmt?',
    claim: 'Ich übernehme',
    mine: 'Du übernimmst das.',
    byOther: (name: string) => `Übernimmt: ${name}`,
    formerMember: 'ehemaliges Mitglied',
    releaseMine: 'Doch nicht – wieder freigeben',
    release: 'Freigeben',
    releaseTitle: (name: string) => `Zusage von ${name} aufheben?`,
    releaseText: 'Der Termin ist danach wieder offen.',
    taken: 'Schon vergeben – jemand anderes war schneller.',
  },
  overview: {
    filters: {
      all: (n: number) => `Alle (${n})`,
      open: (n: number) => `Offen (${n})`,
      mine: (n: number) => `Meine (${n})`,
    },
    empty: {
      all: 'In den nächsten 14 Tagen steht nichts an.',
      open: 'Alles vergeben – in den nächsten 14 Tagen ist nichts mehr offen.',
      mine: 'Du hast in den nächsten 14 Tagen nichts übernommen.',
    },
  },
  calendar: {
    months: [
      'Januar',
      'Februar',
      'März',
      'April',
      'Mai',
      'Juni',
      'Juli',
      'August',
      'September',
      'Oktober',
      'November',
      'Dezember',
    ],
    weekdaysShort: ['Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa', 'So'],
    previous: 'Voriger Monat',
    next: 'Nächster Monat',
    noneOnDay: 'An diesem Tag steht nichts an.',
    upcoming: 'Die nächsten 14 Tage',
    dayA11y: (d: Date, open: number, covered: number) =>
      [
        `${d.getDate()}. ${t.calendar.months[d.getMonth()]}`,
        open ? `${open} offen` : null,
        covered ? `${covered} vergeben` : null,
      ]
        .filter(Boolean)
        .join(', '),
  },
  dateField: {
    choose: 'Datum wählen',
  },
  timeField: {
    choose: 'Uhrzeit wählen',
    hour: 'Stunde',
    minute: 'Minute',
    apply: 'Übernehmen',
    incomplete: 'Bitte Stunde und Minute antippen.',
    hourA11y: (h: number) => `${h} Uhr`,
    minuteA11y: (m: number) => `${m} Minuten`,
  },
  header: {
    menu: 'Menü öffnen',
    search: 'Suchen',
    today: 'Heute',
    toggleCalendar: (expanded: boolean) =>
      expanded ? 'Kalender einklappen' : 'Kalender ausklappen',
  },
  menu: {
    title: 'Menü',
  },
  search: {
    title: 'Suchen',
    placeholder: 'Termin, Kind, Ort oder Person',
    hint: 'Durchsucht alle Termine der nächsten 12 Monate.',
    none: 'Nichts gefunden.',
    more: (n: number) => `… und ${n} weitere. Bitte genauer suchen.`,
  },
  familyScreen: {
    title: 'Familie',
  },
  update: {
    title: 'Update nötig',
    text: 'Diese Version wird nicht mehr unterstützt. Bitte aktualisiere die App im Play Store.',
    button: 'Zum Play Store',
  },
} as const;
