-- Step 4: concrete occurrences, precomputed 8 weeks ahead from the event rules.

create extension if not exists pg_cron;

create type public.occurrence_status as enum ('open', 'claimed', 'cancelled');

create table public.occurrences (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.events (id) on delete cascade,
  family_id uuid not null references public.families (id) on delete cascade,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  status public.occurrence_status not null default 'open',
  assigned_to uuid references public.profiles (id) on delete set null,
  note text check (char_length(note) <= 200),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (event_id, starts_at)
);

create index occurrences_family_starts_idx on public.occurrences (family_id, starts_at);

alter table public.occurrences enable row level security;

-- Members read. No insert/update/delete policies: occurrences are generated by the
-- functions below and changed only via cancel_occurrence (and claim/release in step 5).
create policy "occurrences_select_members" on public.occurrences
  for select to authenticated
  using (public.is_family_member(family_id));

-- Creates the missing occurrences of one event for local dates in [p_from, p_to).
-- Wall-clock time in the event's timezone: "15:00" stays 15:00 across DST changes.
create function public.generate_occurrences_for(p_event_id uuid, p_from date, p_to date)
returns void
language sql
volatile
security definer
set search_path = ''
as $$
  insert into public.occurrences (event_id, family_id, starts_at, ends_at)
  select e.id,
         e.family_id,
         (d + e.start_time) at time zone e.timezone,
         (d + e.start_time) at time zone e.timezone + make_interval(mins => e.duration_min)
    from public.events e
   -- plain dates (date + integer), independent of the session timezone
   cross join lateral (
     select greatest(e.first_date, p_from) + i as d
       from generate_series(
              0,
              least(coalesce(e.until_date, p_to - 1), p_to - 1) - greatest(e.first_date, p_from)
            ) as i
   ) as days
   where e.id = p_event_id
     and (
       -- one-off: only its date
       (e.rrule is null and d = e.first_date)
       -- weekly (format enforced by the check on events.rrule): ISO weekday in BYDAY
       or (e.rrule is not null and extract(isodow from d)::int = any (
             array(select array_position(array['MO','TU','WE','TH','FR','SA','SU'], day)
                     from unnest(string_to_array(replace(e.rrule, 'FREQ=WEEKLY;BYDAY=', ''), ',')) as day)))
     )
  on conflict (event_id, starts_at) do nothing;
$$;

-- Daily job: keep the next 8 weeks precomputed for all events.
create function public.generate_occurrences()
returns void
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  e record;
  v_today date;
begin
  for e in select id, timezone from public.events loop
    v_today := (now() at time zone e.timezone)::date;
    perform public.generate_occurrences_for(e.id, v_today, v_today + 56);
  end loop;
end;
$$;

-- New or changed event: its occurrences appear immediately, not only after the next job run.
-- On a change, future occurrences nobody has taken yet are rebuilt from the new rule;
-- claimed and cancelled ones are kept.
create function public.handle_event_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_today date := (now() at time zone new.timezone)::date;
begin
  if tg_op = 'UPDATE' then
    delete from public.occurrences
     where event_id = new.id
       and status = 'open'
       and assigned_to is null
       and starts_at > now();
  end if;
  perform public.generate_occurrences_for(new.id, v_today, v_today + 56);
  return new;
end;
$$;

create trigger on_event_change
  after insert or update of start_time, duration_min, timezone, rrule, first_date, until_date
  on public.events
  for each row execute function public.handle_event_change();

-- Parents cancel a single occurrence.
create function public.cancel_occurrence(p_occurrence_id uuid)
returns void
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_family_id uuid;
begin
  select family_id into v_family_id from public.occurrences where id = p_occurrence_id;
  if v_family_id is null or not public.is_family_parent(v_family_id) then
    raise exception 'only parents can cancel' using errcode = '42501';
  end if;
  update public.occurrences
     set status = 'cancelled', updated_at = now()
   where id = p_occurrence_id;
end;
$$;

revoke execute on function public.generate_occurrences_for(uuid, date, date) from public, anon, authenticated;
revoke execute on function public.generate_occurrences() from public, anon, authenticated;
revoke execute on function public.cancel_occurrence(uuid) from public, anon;
grant execute on function public.cancel_occurrence(uuid) to authenticated;

-- 02:15 UTC = 03:15/04:15 in Berlin
select cron.schedule('generate-occurrences', '15 2 * * *', 'select public.generate_occurrences()');

-- Events that already exist get their occurrences now.
select public.generate_occurrences();
